#!/usr/bin/env python3
"""Create MCQ Jupyter notebooks parts 6-10 with 100 questions each."""
import json
import os

TEMPLATE = {
    "cells": [],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

def cell(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines]}

def add_q(nb, n, q, opts, ans, exp):
    lines = [f"### Q{n}. {q}", ""] + [f"- {c}) {t}" for c, t in opts] + [
        "", "<details>", "<summary>Show Answer</summary>", "",
        f"**Q{n}. {ans})** {exp}", "", "</details>"
    ]
    nb["cells"].append(cell(lines))

# Part 6: Modules, Packages & Standard Library (Q501-Q600)
P6 = [
    ("What does `__name__ == '__main__'` check?", [("A", "Script run directly"), ("B", "Module imported"), ("C", "Both A and B"), ("D", "Neither")], "A", "True when script is executed directly, not imported."),
    ("What is `__init__.py` used for?", [("A", "Package marker"), ("B", "Package initialization"), ("C", "Both A and B"), ("D", "Module only")], "C", "Marks directory as package and can run init code."),
    ("What does `from . import foo` mean?", [("A", "Absolute import"), ("B", "Relative import from same package"), ("C", "Import from parent"), ("D", "Import from root")], "B", "Dot means relative import within same package."),
    ("Where does Python look for modules first?", [("A", "sys.path"), ("B", "PYTHONPATH only"), ("C", "Current dir only"), ("D", "site-packages only")], "A", "sys.path lists directories searched for imports."),
    ("What does `os.path.join('a', 'b', 'c')` return on Windows?", [("A", "'a\\\\b\\\\c'"), ("B", "'a/b/c'"), ("C", "'a-b-c'"), ("D", "Depends on OS")], "D", "join uses OS-specific separator."),
    ("What does `sys.argv[0]` contain?", [("A", "First argument"), ("B", "Script name"), ("C", "Python path"), ("D", "Empty")], "B", "argv[0] is the script filename."),
    ("What is `datetime.datetime.now()`?", [("A", "Current date only"), ("B", "Current time only"), ("C", "Current date and time"), ("D", "UTC time")], "C", "now() returns current local datetime."),
    ("What does `math.ceil(2.3)` return?", [("A", "2"), ("B", "3"), ("C", "2.0"), ("D", "2.3")], "B", "ceil rounds up to nearest integer."),
    ("What does `random.randint(1, 10)` include?", [("A", "1 only"), ("B", "10 only"), ("C", "Both 1 and 10"), ("D", "Neither")], "C", "randint is inclusive on both ends."),
    ("What is `collections.Counter('aab')`?", [("A", "Counter({'a': 2, 'b': 1})"), ("B", "['a','a','b']"), ("C", "3"), ("D", "Error")], "A", "Counter counts occurrences of each element."),
    ("What does `defaultdict(int)` provide?", [("A", "Default 0 for missing keys"), ("B", "Default 1"), ("C", "Raises KeyError"), ("D", "Returns None")], "A", "defaultdict(int) uses int() = 0 for missing keys."),
    ("What is `collections.deque`?", [("A", "Double-ended queue"), ("B", "Stack only"), ("C", "List only"), ("D", "Set")], "A", "deque supports O(1) append/pop from both ends."),
    ("What does `pathlib.Path('a/b').parent` return?", [("A", "Path('a')"), ("B", "Path('a/b')"), ("C", "Path('.')"), ("D", "'a'")], "A", "parent is the directory containing the path."),
    ("What does `shutil.copy(src, dst)` do?", [("A", "Copy file"), ("B", "Copy directory"), ("C", "Move file"), ("D", "Delete file")], "A", "shutil.copy copies a single file."),
    ("What does `subprocess.run(['ls'])` return?", [("A", "Output string"), ("B", "CompletedProcess"), ("C", "None"), ("D", "Exit code only")], "B", "run() returns CompletedProcess instance."),
    ("What is `venv` used for?", [("A", "Virtual environment"), ("B", "Version control"), ("C", "Package manager"), ("D", "IDE")], "A", "venv creates isolated Python environments."),
    ("What does `pip install -e .` do?", [("A", "Editable install"), ("B", "Upgrade package"), ("C", "Uninstall"), ("D", "List packages")], "A", "Editable mode links to source for development."),
    ("What is PyPI?", [("A", "Python Package Index"), ("B", "Package installer"), ("C", "Virtual env"), ("D", "IDE")], "A", "PyPI is the default package repository."),
    ("What does `import x as y` do?", [("A", "Import x with alias y"), ("B", "Import y as x"), ("C", "Import both"), ("D", "Error")], "A", "Binds imported module to name y."),
    ("What is `sys.modules`?", [("A", "Dict of loaded modules"), ("B", "List of paths"), ("C", "Module names"), ("D", "Import cache")], "A", "sys.modules maps module names to loaded modules."),
    ("What does `os.environ.get('HOME')` return?", [("A", "Current directory"), ("B", "Home directory path"), ("C", "Username"), ("D", "Always None")], "B", "HOME env var contains user home path."),
    ("What is `sys.exit(1)`?", [("A", "Exit with code 1"), ("B", "Raise SystemExit"), ("C", "Both A and B"), ("D", "Pause program")], "C", "Raises SystemExit, non-zero indicates error."),
    ("What does `datetime.timedelta(days=1)` represent?", [("A", "1 day duration"), ("B", "Current date"), ("C", "Tomorrow"), ("D", "Yesterday")], "A", "timedelta represents a duration."),
    ("What is `math.isnan(x)` for?", [("A", "Check if x is NaN"), ("B", "Convert to int"), ("C", "Round"), ("D", "Absolute value")], "A", "isnan returns True for NaN values."),
    ("What does `random.choice([1,2,3])` return?", [("A", "List"), ("B", "One element"), ("C", "Shuffled list"), ("D", "Index")], "B", "choice returns one random element."),
    ("What is `OrderedDict` (Python 3.7+)?", [("A", "dict preserves order"), ("B", "OrderedDict redundant"), ("C", "Both A and B"), ("D", "Only for sorting")], "C", "Regular dict is ordered since 3.7; OrderedDict still has extra methods."),
    ("What does `Path('file.txt').exists()` return?", [("A", "True if file exists"), ("B", "Always True"), ("C", "File content"), ("D", "Path object")], "A", "exists() checks if path exists on filesystem."),
    ("What does `shutil.rmtree(path)` do?", [("A", "Remove directory tree"), ("B", "Remove single file"), ("C", "Rename"), ("D", "Copy")], "A", "rmtree recursively deletes directory."),
    ("What does `subprocess.run(..., capture_output=True)` do?", [("A", "Capture stdout/stderr"), ("B", "Run in background"), ("C", "Pipe only"), ("D", "Nothing")], "A", "capture_output=True captures output."),
    ("What is `pip freeze`?", [("A", "List installed packages"), ("B", "Stop pip"), ("C", "Install frozen"), ("D", "Upgrade all")], "A", "freeze outputs installed packages with versions."),
    ("What does `from package import *` import?", [("A", "All from __all__ or all public"), ("B", "Nothing"), ("C", "Only __init__"), ("D", "Private names")], "A", "Imports names in __all__ or non-underscore names."),
    ("What is `__file__` in a module?", [("A", "Path to module file"), ("B", "Filename only"), ("C", "Import path"), ("D", "None")], "A", "__file__ is the path of the current module."),
    ("What does `os.getcwd()` return?", [("A", "Current working directory"), ("B", "Script directory"), ("C", "Home directory"), ("D", "Temp directory")], "A", "getcwd returns current working directory."),
    ("What does `sys.stdin` represent?", [("A", "Standard input stream"), ("B", "File handle"), ("C", "Both A and B"), ("D", "Keyboard only")], "C", "stdin is the standard input file object."),
    ("What is `datetime.strptime('2024-01-15', '%Y-%m-%d')`?", [("A", "Parse string to datetime"), ("B", "Format datetime"), ("C", "Current date"), ("D", "Error")], "A", "strptime parses string to datetime."),
    ("What does `math.inf` represent?", [("A", "Positive infinity"), ("B", "Negative infinity"), ("C", "NaN"), ("D", "Max float")], "A", "math.inf is positive infinity."),
    ("What does `random.shuffle(lst)` return?", [("A", "Shuffled list"), ("B", "None"), ("C", "Original list"), ("D", "New list")], "B", "shuffle mutates in place, returns None."),
    ("What is `Counter.most_common(2)`?", [("A", "Top 2 most frequent"), ("B", "First 2 elements"), ("C", "Last 2"), ("D", "2 random")], "A", "most_common(n) returns n most common."),
    ("What does `defaultdict(list)` use for missing keys?", [("A", "[]"), ("B", "None"), ("C", "{}"), ("D", "Raises KeyError")], "A", "defaultdict(list) uses list() = [] for missing keys."),
    ("What is `deque.popleft()`?", [("A", "Remove from left"), ("B", "Remove from right"), ("C", "Peek left"), ("D", "Add left")], "A", "popleft removes and returns leftmost element."),
    ("What does `Path('a/b/c.txt').suffix` return?", [("A", "'.txt'"), ("B", "'c.txt'"), ("C", "'txt'"), ("D", "'a/b'")], "A", "suffix is the file extension including dot."),
    ("What does `shutil.move(src, dst)` do?", [("A", "Move file/dir"), ("B", "Copy only"), ("C", "Rename only"), ("D", "Delete")], "A", "move can rename or relocate."),
    ("What does `subprocess.Popen` return?", [("A", "Process object"), ("B", "Output"), ("C", "Exit code"), ("D", "None")], "A", "Popen returns Popen instance for async control."),
    ("What is `python -m venv myenv`?", [("A", "Create venv named myenv"), ("B", "Activate venv"), ("C", "Delete venv"), ("D", "List venvs")], "A", "Creates virtual environment in myenv/."),
    ("What does `pip install package==1.0.0` do?", [("A", "Install exact version"), ("B", "Upgrade to latest"), ("C", "Uninstall"), ("D", "Check version")], "A", "== pins to exact version."),
    ("What is `importlib.import_module(name)`?", [("A", "Dynamic import"), ("B", "Reload module"), ("C", "List modules"), ("D", "Import path")], "A", "Dynamically imports module by string name."),
    ("What does `os.path.abspath('x')` return?", [("A", "Absolute path"), ("B", "Relative path"), ("C", "Resolved path"), ("D", "Canonical path")], "A", "abspath converts to absolute path."),
    ("What does `sys.getsizeof(x)` return?", [("A", "Object size in bytes"), ("B", "Length"), ("C", "Memory address"), ("D", "Type size")], "A", "getsizeof returns approximate size in bytes."),
    ("What is `datetime.timezone.utc`?", [("A", "UTC timezone"), ("B", "Local timezone"), ("C", "Offset only"), ("D", "DST info")], "A", "Represents UTC timezone."),
    ("What does `math.gcd(12, 8)` return?", [("A", "4"), ("B", "2"), ("C", "96"), ("D", "20")], "A", "gcd returns greatest common divisor."),
    ("What does `random.sample([1,2,3], 2)` return?", [("A", "2 unique elements"), ("B", "2 with replacement"), ("C", "List of 2 lists"), ("D", "Error")], "A", "sample returns k unique elements."),
    ("What is `Counter + Counter`?", [("A", "Add counts"), ("B", "Merge keys"), ("C", "Error"), ("D", "Union")], "A", "Adding Counters sums counts per key."),
    ("What does `defaultdict(lambda: 'default')` use?", [("A", "'default' for missing"), ("B", "None"), ("C", "Raises"), ("D", "0")], "A", "lambda provides custom default factory."),
    ("What is `deque(maxlen=3)`?", [("A", "Bounded deque"), ("B", "Min length 3"), ("C", "Fixed size 3"), ("D", "Error")], "A", "maxlen limits size; oldest dropped when full."),
    ("What does `Path.iterdir()` return?", [("A", "Iterator of paths"), ("B", "List of names"), ("C", "Single path"), ("D", "Generator")], "A", "iterdir yields child paths."),
    ("What does `shutil.copytree(src, dst)` do?", [("A", "Copy directory tree"), ("B", "Copy one file"), ("C", "Move tree"), ("D", "Merge trees")], "A", "copytree recursively copies directory."),
    ("What does `subprocess.run(..., check=True)` do on non-zero exit?", [("A", "Raise CalledProcessError"), ("B", "Return anyway"), ("C", "Retry"), ("D", "Ignore")], "A", "check=True raises on non-zero exit."),
    ("What is `pip list`?", [("A", "List installed packages"), ("B", "List available"), ("C", "List requirements"), ("D", "List versions")], "A", "list shows installed packages."),
    ("What does `from .submodule import x` mean?", [("A", "Relative import from submodule"), ("B", "Absolute import"), ("C", "Import parent"), ("D", "Import x from current")], "A", "Imports x from submodule in same package."),
    ("What is `__package__`?", [("A", "Package name of module"), ("B", "Import path"), ("C", "Both"), ("D", "Package dir")], "A", "__package__ is the package name."),
    ("What does `os.listdir('.')` return?", [("A", "List of names in dir"), ("B", "List of paths"), ("C", "Iterator"), ("D", "Single name")], "A", "listdir returns names (not full paths)."),
    ("What does `sys.version` contain?", [("A", "Python version string"), ("B", "Version number only"), ("C", "Build info"), ("D", "All of above")], "A", "version is full version string."),
    ("What is `datetime.datetime.utcnow()`?", [("A", "Deprecated, use datetime.now(timezone.utc)"), ("B", "Current UTC"), ("C", "Both"), ("D", "Local time")], "C", "utcnow is deprecated; use timezone-aware."),
    ("What does `math.sqrt(-1)` return?", [("A", "ValueError"), ("B", "NaN"), ("C", "0"), ("D", "1j")], "B", "sqrt of negative returns float NaN."),
    ("What does `random.seed(42)` do?", [("A", "Reproducible randomness"), ("B", "Set max random"), ("C", "Initialize only once"), ("D", "Nothing")], "A", "seed makes random sequence reproducible."),
    ("What is `Counter.elements()`?", [("A", "Iterator over elements by count"), ("B", "List of keys"), ("C", "Sum of counts"), ("D", "Unique elements")], "A", "elements() yields each element count times."),
    ("What does `defaultdict(set)` use for missing keys?", [("A", "set()"), ("B", "{}"), ("C", "None"), ("D", "[]")], "A", "set() creates empty set."),
    ("What is `deque.rotate(1)`?", [("A", "Rotate right by 1"), ("B", "Rotate left"), ("C", "Sort"), ("D", "Reverse")], "A", "rotate(1) moves last to first."),
    ("What does `Path.read_text()` return?", [("A", "File content as str"), ("B", "Bytes"), ("C", "Lines list"), ("D", "File object")], "A", "read_text reads and decodes to string."),
    ("What does `os.path.exists(path)` return?", [("A", "True if path exists"), ("B", "Always bool"), ("C", "Both"), ("D", "Path object")], "C", "Returns True/False for existence."),
    ("What does `sys.platform` contain?", [("A", "OS identifier"), ("B", "Python version"), ("C", "Architecture"), ("D", "Compiler")], "A", "e.g. 'win32', 'linux', 'darwin'."),
    ("What is `datetime.date.today()`?", [("A", "Current date"), ("B", "Current datetime"), ("C", "Date string"), ("D", "Timestamp")], "A", "today() returns current date object."),
    ("What does `math.floor(-2.3)` return?", [("A", "-2"), ("B", "-3"), ("C", "-2.0"), ("D", "2")], "B", "floor rounds down (toward -inf)."),
    ("What does `random.random()` return?", [("A", "Float in [0, 1)"), ("B", "Int 0 or 1"), ("C", "Float in (0, 1]"), ("D", "Any float")], "A", "random() returns float in [0, 1)."),
    ("What is `collections.namedtuple`?", [("A", "Tuple with named fields"), ("B", "Dict-like tuple"), ("C", "Both"), ("D", "Ordered dict")], "A", "namedtuple adds field names to tuple."),
    ("What does `Path.glob('*.py')` return?", [("A", "Iterator of matching paths"), ("B", "List"), ("C", "Single path"), ("D", "Bool")], "A", "glob yields paths matching pattern."),
    ("What does `os.makedirs('a/b/c', exist_ok=True)` do?", [("A", "Create dirs, no error if exists"), ("B", "Create only if not exists"), ("C", "Replace existing"), ("D", "Create single dir")], "A", "exist_ok=True avoids FileExistsError."),
    ("What does `sys.executable` contain?", [("A", "Python interpreter path"), ("B", "Script path"), ("C", "Module path"), ("D", "venv path")], "A", "Path to python executable."),
    ("What is `datetime.timedelta.total_seconds()`?", [("A", "Total seconds as float"), ("B", "Seconds component only"), ("C", "Days only"), ("D", "Integer seconds")], "A", "total_seconds returns duration in seconds."),
    ("What does `math.pow(2, 3)` return?", [("A", "8.0"), ("B", "8"), ("C", "6"), ("D", "9")], "A", "pow returns float (2**3 = 8.0)."),
    ("What does `random.uniform(1, 10)` return?", [("A", "Float in [1, 10]"), ("B", "Int in [1, 10]"), ("C", "Float in (1, 10)"), ("D", "Always 5.5")], "A", "uniform returns float in inclusive range."),
    ("What is `collections.ChainMap`?", [("A", "Dict-like view of multiple dicts"), ("B", "Chained list"), ("C", "Linked dict"), ("D", "Merge dicts")], "A", "ChainMap looks up in multiple dicts."),
    ("What does `Path.write_text('hello')` do?", [("A", "Write string to file"), ("B", "Append"), ("C", "Read first"), ("D", "Create dir only")], "A", "write_text writes string, overwrites."),
    ("What does `os.path.basename('/a/b/c.txt')` return?", [("A", "'c.txt'"), ("B", "'/a/b'"), ("C", "'c'"), ("D", "'a'")], "A", "basename is the final component."),
    ("What does `sys.getrecursionlimit()` return?", [("A", "Max recursion depth"), ("B", "Stack size"), ("C", "Call limit"), ("D", "Default 1000")], "A", "Default is typically 1000."),
    ("What is `datetime.datetime.fromtimestamp(0)`?", [("A", "Epoch in local time"), ("B", "Epoch in UTC"), ("C", "Current time"), ("D", "Error")], "A", "fromtimestamp uses local timezone."),
    ("What does `math.factorial(5)` return?", [("A", "120"), ("B", "5"), ("C", "15"), ("D", "25")], "A", "5! = 5*4*3*2*1 = 120."),
    ("What does `random.getrandbits(8)` return?", [("A", "Int with 8 random bits"), ("B", "Byte"), ("C", "Float"), ("D", "8 random ints")], "A", "Returns int with k random bits."),
    ("What is `collections.UserDict`?", [("A", "Base for dict subclasses"), ("B", "User-defined dict"), ("C", "Both"), ("D", "Custom key type")], "A", "UserDict simplifies dict subclassing."),
    ("What does `Path.mkdir(parents=True)` do?", [("A", "Create parent dirs too"), ("B", "Create only parents"), ("C", "Ignore existing"), ("D", "Create single dir")], "A", "parents=True creates intermediate dirs."),
    ("What does `os.chdir(path)` do?", [("A", "Change current directory"), ("B", "Create directory"), ("C", "Check directory"), ("D", "List directory")], "A", "chdir changes cwd."),
    ("What does `sys.getdefaultencoding()` return?", [("A", "'utf-8'"), ("B", "'ascii'"), ("C", "Platform-dependent"), ("D", "None")], "A", "Default is utf-8 in Python 3."),
    ("What is `datetime.datetime.combine(date, time)`?", [("A", "Combine date and time"), ("B", "Split datetime"), ("C", "Compare"), ("D", "Format")], "A", "Creates datetime from date and time."),
    ("What does `math.copysign(5, -1)` return?", [("A", "-5.0"), ("B", "5.0"), ("C", "-1"), ("D", "5")], "A", "copysign uses magnitude of first, sign of second."),
    ("What does `random.gauss(0, 1)` return?", [("A", "Gaussian random"), ("B", "Uniform"), ("C", "Integer"), ("D", "List")], "A", "gauss returns normal distribution sample."),
    ("What is `functools.lru_cache`?", [("A", "Memoization decorator"), ("B", "Cache module"), ("C", "LRU list"), ("D", "Memory cache")], "A", "lru_cache caches function results."),
    ("What does `Path.resolve()` return?", [("A", "Absolute resolved path"), ("B", "Relative path"), ("C", "Symlink target"), ("D", "String")], "A", "resolve() returns absolute path, resolving symlinks."),
    ("What does `os.path.isfile(path)` return?", [("A", "True if regular file"), ("B", "True if exists"), ("C", "File size"), ("D", "Extension")], "A", "isfile checks if path is regular file."),
    ("What does `sys.path.insert(0, dir)` do?", [("A", "Prepend dir to search path"), ("B", "Append dir"), ("C", "Replace path"), ("D", "Remove dir")], "A", "insert(0,...) adds at front of sys.path."),
    ("What is `datetime.timezone(datetime.timedelta(hours=-5))`?", [("A", "Fixed offset timezone"), ("B", "UTC"), ("C", "Local"), ("D", "DST-aware")], "A", "Fixed offset from UTC (e.g. EST)."),
    ("What does `math.log(8, 2)` return?", [("A", "3.0"), ("B", "4.0"), ("C", "2.0"), ("D", "8.0")], "A", "log(8,2) = log2(8) = 3."),
    ("What does `random.choices([1,2,3], k=2)` return?", [("A", "List of 2 (with replacement)"), ("B", "2 unique"), ("C", "Generator"), ("D", "Error")], "A", "choices allows duplicates."),
    ("What is `importlib.reload(module)`?", [("A", "Reload module"), ("B", "Import again"), ("C", "Both"), ("D", "Clear cache")], "A", "reload re-executes module code."),
    ("What does `Path.with_suffix('.txt')` do?", [("A", "Return new path with new suffix"), ("B", "Rename file"), ("C", "Modify in place"), ("D", "Add suffix")], "A", "Returns new Path with changed suffix."),
    ("What does `os.path.getsize(path)` return?", [("A", "File size in bytes"), ("B", "Line count"), ("C", "Block size"), ("D", "Inode")], "A", "getsize returns size in bytes."),
    ("What does `sys.setrecursionlimit(2000)` do?", [("A", "Set max recursion depth"), ("B", "Increase stack"), ("C", "Both"), ("D", "Nothing")], "A", "Changes recursion limit (use carefully)."),
    ("What is `datetime.datetime.isoformat()`?", [("A", "ISO 8601 string"), ("B", "Custom format"), ("C", "Timestamp"), ("D", "Date only")], "A", "Returns e.g. '2024-01-15T10:30:00'."),
    ("What does `math.degrees(math.pi)` return?", [("A", "180.0"), ("B", "90.0"), ("C", "3.14"), ("D", "360.0")], "A", "pi radians = 180 degrees."),
    ("What does `hash(random.random())` do?", [("A", "Hash the float"), ("B", "Error"), ("C", "Same each time"), ("D", "Returns int")], "A", "hash() works on hashable types; float is hashable."),
    ("What is `pkgutil.iter_modules()`?", [("A", "Iterate over importable modules"), ("B", "List packages"), ("C", "Import all"), ("D", "Find modules")], "A", "Iterates modules in a path."),
    ("What does `Path.is_absolute()` return?", [("A", "True if absolute path"), ("B", "True if exists"), ("C", "True if file"), ("D", "Path object")], "A", "Checks if path is absolute."),
    ("What does `os.path.dirname('/a/b/c.txt')` return?", [("A", "'/a/b'"), ("B", "'c.txt'"), ("C", "'a'"), ("D", "''")], "A", "dirname is directory part."),
    ("What does `sys.getrefcount(x)` return?", [("A", "Reference count"), ("B", "Memory address"), ("C", "Size"), ("D", "Type id")], "A", "Returns number of references to object."),
    ("What does `list(collections.Counter('aab').elements())` produce?", [("A", "['a','a','b']"), ("B", "[2,1]"), ("C", "['a','b']"), ("D", "Error")], "A", "elements() yields each item by its count."),
    ("What is `from .. import foo`?", [("A", "Import from parent package"), ("B", "Import from child"), ("C", "Absolute import"), ("D", "Error")], "A", "Double dot means parent package."),
    ("What does `os.path.splitext('file.txt')` return?", [("A", "('file', '.txt')"), ("B", "['file','txt']"), ("C", "'file'"), ("D", "'txt'")], "A", "splitext splits base and extension."),
    ("What does `sys.path.append(dir)` do?", [("A", "Add dir to end of search path"), ("B", "Prepend dir"), ("C", "Replace path"), ("D", "Remove dir")], "A", "append adds to end of sys.path."),
    ("What is `datetime.datetime.strftime`?", [("A", "Format datetime to string"), ("B", "Parse string"), ("C", "Current time"), ("D", "Timestamp")], "A", "strftime formats datetime to string."),
    ("What does `math.radians(180)` return?", [("A", "3.14159..."), ("B", "90.0"), ("C", "180.0"), ("D", "0.0")], "A", "180 degrees = pi radians."),
    ("What does `random.choices([1,2,3], weights=[1,2,1])` use?", [("A", "Weighted random selection"), ("B", "Equal weights"), ("C", "Error"), ("D", "Index")], "A", "weights bias selection probability."),
    ("What is `collections.Counter('abracadabra').most_common(1)`?", [("A", "[('a', 5)]"), ("B", "[('a','b','r')]"), ("C", "11"), ("D", "Error")], "A", "most_common(1) returns single most frequent."),
    ("What does `Path.touch()` do?", [("A", "Create empty file or update mtime"), ("B", "Delete file"), ("C", "Read file"), ("D", "Copy file")], "A", "touch creates file if missing or updates timestamp."),
]

# Part 7: Decorators, Generators & Metaprogramming (Q601-Q700)
P7 = [
    ("What does a decorator do?", [("A", "Wrap/modify function"), ("B", "Delete function"), ("C", "Import function"), ("D", "Call function")], "A", "Decorator wraps and can modify function behavior."),
    ("What does `functools.wraps(f)` preserve?", [("A", "Original metadata"), ("B", "Function body"), ("C", "Return value"), ("D", "Arguments")], "A", "wraps copies __name__, __doc__, etc."),
    ("What does `@property` create?", [("A", "Getter for attribute"), ("B", "Setter only"), ("C", "Both getter and optional setter"), ("D", "Class method")], "C", "property defines getter; setter/deleter optional."),
    ("What is a descriptor?", [("A", "Object with __get__/__set__/__delete__"), ("B", "Decorator"), ("C", "Property only"), ("D", "Method")], "A", "Descriptor protocol: __get__, __set__, __delete__."),
    ("What does `type()` with 3 args create?", [("A", "New class dynamically"), ("B", "Instance"), ("C", "Type object"), ("D", "Metaclass")], "A", "type(name, bases, dict) creates a class."),
    ("What is `__new__` vs `__init__`?", [("A", "__new__ creates, __init__ initializes"), ("B", "Same thing"), ("C", "__init__ first"), ("D", "Only __init__ needed")], "A", "__new__ creates object; __init__ sets up."),
    ("What does `__slots__` do?", [("A", "Restrict instance attributes"), ("B", "Add attributes"), ("C", "Create slots"), ("D", "Reserve memory")], "A", "__slots__ limits allowed attributes, saves memory."),
    ("What does `yield` do in a function?", [("A", "Pause and return value"), ("B", "Return and stop"), ("C", "Raise exception"), ("D", "Break loop")], "A", "yield makes generator; pauses and yields value."),
    ("What does `generator.send(x)` do?", [("A", "Send value into yield"), ("B", "Send to next"), ("C", "Both"), ("D", "Raise error")], "A", "send() passes value to yield expression."),
    ("What does `generator.throw(exc)` do?", [("A", "Raise exception in generator"), ("B", "Catch exception"), ("C", "Return exception"), ("D", "Ignore")], "A", "throw raises exception at yield point."),
    ("What is `(x**2 for x in range(5))`?", [("A", "Generator expression"), ("B", "List"), ("C", "Tuple"), ("D", "Set")], "A", "Parentheses create generator expression."),
    ("What is `abc.ABC`?", [("A", "Abstract base class"), ("B", "Abstract method"), ("C", "Base class only"), ("D", "Interface")], "A", "ABC is base for abstract classes."),
    ("What does `__init_subclass__` do?", [("A", "Hook when subclass is created"), ("B", "Initialize subclass"), ("C", "Call super"), ("D", "Register class")], "A", "Called when class is subclassed."),
    ("What is `__class_getitem__`?", [("A", "Support cls[int]"), ("B", "Get class item"), ("C", "Generic type"), ("D", "Index class")], "A", "Enables Class[int] syntax for generics."),
    ("What does a decorator with args look like?", [("A", "@decorator(arg)"), ("B", "@decorator"), ("C", "Both"), ("D", "decorator()")], "A", "decorator(arg) returns actual decorator."),
    ("What does `@staticmethod` do?", [("A", "No self/cls"), ("B", "Class method"), ("C", "Instance only"), ("D", "Abstract")], "A", "staticmethod receives no implicit first arg."),
    ("What is `__get__` in a descriptor?", [("A", "Called on attribute access"), ("B", "Getter method"), ("C", "Both"), ("D", "Property")], "A", "__get__(self, instance, owner) on access."),
    ("What is a metaclass?", [("A", "Class of a class"), ("B", "Base class"), ("C", "Super class"), ("D", "Abstract class")], "A", "Metaclass creates classes; type is default."),
    ("What does `object.__new__(cls)` do?", [("A", "Create instance"), ("B", "Initialize"), ("C", "Both"), ("D", "Return cls")], "A", "__new__ creates and returns new instance."),
    ("What does `__slots__ = ['x']` prevent?", [("A", "Adding other attributes"), ("B", "Using x"), ("C", "Inheritance"), ("D", "Methods")], "A", "Only x (and __dict__-like) allowed."),
    ("What does a generator return?", [("A", "Generator iterator"), ("B", "First value"), ("C", "List"), ("D", "None")], "A", "Generator function returns generator object."),
    ("What does `next(gen)` do?", [("A", "Advance to next yield"), ("B", "Get first only"), ("C", "Reset generator"), ("D", "Close generator")], "A", "next() advances to next yield."),
    ("What is a coroutine?", [("A", "async def function"), ("B", "Generator with send"), ("C", "Both"), ("D", "Thread")], "C", "async def creates coroutine; generators can emulate."),
    ("What does `@abstractmethod` do?", [("A", "Must override in subclass"), ("B", "Cannot call"), ("C", "Both"), ("D", "Optional override")], "A", "Abstract method must be implemented."),
    ("What does `__init_subclass__(cls)` receive?", [("A", "The new subclass"), ("B", "Parent class"), ("C", "Instance"), ("D", "Nothing")], "A", "cls is the newly defined subclass."),
    ("What does `list[int]` use?", [("A", "__class_getitem__"), ("B", "__getitem__"), ("C", "__subscript__"), ("D", "Generic")], "A", "__class_getitem__ enables Class[args]."),
    ("What does `def dec(f): return f` do?", [("A", "No-op decorator"), ("B", "Replace function"), ("C", "Delete function"), ("D", "Error")], "A", "Returns same function unchanged."),
    ("What does `@classmethod` receive as first arg?", [("A", "cls"), ("B", "self"), ("C", "class"), ("D", "None")], "A", "classmethod gets class as first argument."),
    ("What is `__set__` in a descriptor?", [("A", "Called on assignment"), ("B", "Setter"), ("C", "Both"), ("D", "Property setter")], "A", "__set__(self, instance, value) on assignment."),
    ("What does `type.__new__` create?", [("A", "New class"), ("B", "Instance"), ("C", "Metaclass"), ("D", "Object")], "A", "Metaclass __new__ creates the class object."),
    ("When is `__new__` called?", [("A", "Before __init__"), ("B", "After __init__"), ("C", "Instead of __init__"), ("D", "Never")], "A", "__new__ creates object; __init__ initializes it."),
    ("What does `__slots__` save?", [("A", "Memory"), ("B", "Speed"), ("C", "Both"), ("D", "Neither")], "C", "No __dict__ per instance saves memory."),
    ("What does `yield from iter` do?", [("A", "Delegate to sub-generator"), ("B", "Yield iter"), ("C", "Flatten"), ("D", "Error")], "A", "yield from delegates to another generator."),
    ("What does `gen.close()` do?", [("A", "Raise GeneratorExit"), ("B", "Delete generator"), ("C", "Return None"), ("D", "Pause")], "A", "close() raises GeneratorExit in generator."),
    ("What is `async def`?", [("A", "Coroutine function"), ("B", "Generator"), ("C", "Thread"), ("D", "Process")], "A", "async def defines coroutine function."),
    ("What does `ABC` prevent?", [("A", "Instantiating with unimplemented abstract methods"), ("B", "Subclassing"), ("C", "Importing"), ("D", "Inheritance")], "A", "Cannot instantiate until abstract methods implemented."),
    ("What does `__init_subclass__` replace?", [("A", "Metaclass for simple cases"), ("B", "__init__"), ("C", "__new__"), ("D", "Nothing")], "A", "Simpler than metaclass for subclass hooks."),
    ("What does `typing.Generic` use?", [("A", "__class_getitem__"), ("B", "__getitem__"), ("C", "Metaclass"), ("D", "Decorator")], "A", "Generic uses __class_getitem__ for Type[T]."),
]

# Pad P7 to 100 with unique questions
P7_EXTRA = [
    ("What does `@functools.lru_cache(maxsize=128)` do?", [("A", "Cache up to 128 results"), ("B", "Cache all"), ("C", "No cache"), ("D", "Cache 128 bytes")], "A", "maxsize limits cache entries."),
    ("What does `@property` setter look like?", [("A", "@propname.setter"), ("B", "@setter"), ("C", "@property.setter"), ("D", "def set_prop")], "A", "Use @propname.setter for setter."),
    ("What is `__delete__` in descriptor?", [("A", "Called on del attr"), ("B", "Delete descriptor"), ("C", "Remove"), ("D", "Clear")], "A", "__delete__ called on del instance.attr."),
    ("What is `type('MyClass', (), {})`?", [("A", "Dynamic class"), ("B", "Type object"), ("C", "Instance"), ("D", "Error")], "A", "Creates class with given name, bases, dict."),
    ("What does `__new__` return?", [("A", "New instance"), ("B", "None"), ("C", "cls"), ("D", "self")], "A", "__new__ must return new instance."),
    ("Can you add attributes with __slots__?", [("A", "Only listed ones"), ("B", "Any"), ("C", "None"), ("D", "Only in __init__")], "A", "Only attributes in __slots__ allowed."),
    ("What does `for x in gen` do?", [("A", "Iterate yielded values"), ("B", "Get generator"), ("C", "Call gen"), ("D", "Error")], "A", "for loop consumes generator."),
    ("What does `gen.__next__()` do?", [("A", "Same as next(gen)"), ("B", "Reset"), ("C", "Close"), ("D", "Send")], "A", "__next__ is what next() calls."),
    ("What is `@dataclass`?", [("A", "Auto __init__, __repr__"), ("B", "Data only"), ("C", "Both"), ("D", "Frozen only")], "C", "dataclass generates boilerplate."),
    ("What does `__mro__` contain?", [("A", "Method resolution order"), ("B", "Methods"), ("C", "Attributes"), ("D", "Parents")], "A", "__mro__ is resolution order tuple."),
    ("What does `def dec(x): return lambda f: f` create?", [("A", "Decorator factory"), ("B", "Simple decorator"), ("C", "Error"), ("D", "Closure")], "A", "Returns decorator; dec(x) gives actual decorator."),
    ("When is `__get__` called with instance=None?", [("A", "Access via class"), ("B", "Never"), ("C", "On delete"), ("D", "On set")], "A", "Class access: instance is None, owner is class."),
    ("What does `functools.partial(f, 1)(2)` do?", [("A", "Call f(1, 2)"), ("B", "Call f(2)"), ("C", "Error"), ("D", "Return f")], "A", "partial fixes first arg, passes 2 as second."),
    ("What is `StopIteration` in generator?", [("A", "Signal end of iteration"), ("B", "Error only"), ("C", "Pause"), ("D", "Reset")], "A", "Raised when generator exhausts (or return)."),
    ("What does `@abstractmethod` require?", [("A", "ABC base class"), ("B", "Any class"), ("C", "Metaclass"), ("D", "Nothing")], "A", "Abstract methods need ABC (or similar) base."),
    ("What does `__init_subclass__` run?", [("A", "When subclass is defined"), ("B", "When instance created"), ("C", "On import"), ("D", "Never")], "A", "Runs at class definition time."),
    ("What enables `dict[str, int]`?", [("A", "__class_getitem__"), ("B", "__getitem__"), ("C", "typing"), ("D", "Generic")], "A", "__class_getitem__ on built-in types."),
    ("What does `inspect.isfunction(f)` check?", [("A", "f is user-defined function"), ("B", "f is callable"), ("C", "f has __call__"), ("D", "f is method")], "A", "Distinguishes function from built-in, etc."),
    ("What does `yield` without value produce?", [("A", "None"), ("B", "Error"), ("C", "Generator"), ("D", "StopIteration")], "A", "yield yields None when no expression."),
    ("What is `functools.cached_property`?", [("A", "Property cached per instance"), ("B", "Class property"), ("C", "Static cache"), ("D", "LRU property")], "A", "Caches computed value on first access."),
    ("What does `__set_name__` in descriptor do?", [("A", "Receive attribute name"), ("B", "Set name"), ("C", "Rename"), ("D", "Nothing")], "A", "Called when descriptor assigned to class attr."),
    ("What is `type`'s metaclass?", [("A", "type"), ("B", "object"), ("C", "None"), ("D", "type.__class__")], "A", "type is its own metaclass."),
    ("What does `__new__` receive that `__init__` doesn't?", [("A", "cls"), ("B", "Same args"), ("C", "Nothing extra"), ("D", "class")], "A", "__new__ gets cls; __init__ gets self (instance)."),
    ("Can `__slots__` inherit?", [("A", "Yes, child gets parent slots"), ("B", "No"), ("C", "Overrides only"), ("D", "Error")], "A", "Subclass inherits; can add more in own __slots__."),
    ("What does `itertools.islice(gen, 3)` return?", [("A", "First 3 from gen"), ("B", "All from gen"), ("C", "Last 3"), ("D", "Every 3rd")], "A", "islice takes first n from iterator."),
    ("What is `typing.Protocol`?", [("A", "Structural subtyping"), ("B", "Nominal inheritance"), ("C", "Abstract only"), ("D", "Runtime check")], "A", "Protocol enables structural typing (duck typing)."),
    ("What does `__prepare__` in metaclass do?", [("A", "Return namespace for class body"), ("B", "Prepare instance"), ("C", "Init class"), ("D", "Nothing")], "A", "__prepare__ returns dict-like for class namespace."),
    ("What does `generator.gi_frame` hold?", [("A", "Current frame state"), ("B", "Return value"), ("C", "Arguments"), ("D", "Nothing")], "A", "Frame has local vars, etc."),
    ("What is `@functools.singledispatch`?", [("A", "Function overload by first arg type"), ("B", "Single function"), ("C", "Dispatch table"), ("D", "Decorator only")], "A", "Overloads based on type of first argument."),
    ("What does `__getattribute__` intercept?", [("A", "All attribute access"), ("B", "Missing only"), ("C", "Gets only"), ("D", "Sets only")], "A", "__getattribute__ catches every attr access."),
    ("What does `__getattr__` get when attr not found?", [("A", "Last resort"), ("B", "First call"), ("C", "Never"), ("D", "Always")], "A", "__getattr__ only when normal lookup fails."),
    ("What does `class C(metaclass=M)` do?", [("A", "Use M to create C"), ("B", "Inherit M"), ("C", "M is base"), ("D", "M is mixin")], "A", "M is metaclass creating C."),
    ("What does `object.__new__` require?", [("A", "Return instance of cls"), ("B", "Return None"), ("C", "Call __init__"), ("D", "Nothing")], "A", "__new__ must return new instance (or subclass)."),
    ("What happens with `__slots__` and `__dict__`?", [("A", "No __dict__ by default"), ("B", "Both exist"), ("C", "__dict__ only"), ("D", "Error")], "A", "__slots__ removes __dict__ to save memory."),
    ("What does `gen.send(None)` equal?", [("A", "next(gen)"), ("B", "gen.throw()"), ("C", "Error"), ("D", "gen.close()")], "A", "First send must be None (or next())."),
    ("What is `contextlib.contextmanager`?", [("A", "Decorator for generator CM"), ("B", "Base class"), ("C", "Function"), ("D", "Protocol")], "A", "Turns generator into context manager."),
    ("What does `abc.abstractmethod` combine with?", [("A", "ABC"), ("B", "Any class"), ("C", "object"), ("D", "type")], "A", "ABC checks abstract methods at instantiation."),
    ("What does `__init_subclass__` allow?", [("A", "Customize subclass at definition"), ("B", "Only __init__"), ("C", "Only __new__"), ("D", "Runtime only")], "A", "Hook without full metaclass."),
    ("What does `typing.TypeVar` create?", [("A", "Generic type variable"), ("B", "Type alias"), ("C", "New type"), ("D", "Protocol")], "A", "TypeVar for generic type parameters."),
    ("What does `@decorator` without parens mean?", [("A", "decorator(func)"), ("B", "decorator()"), ("C", "Just decorator"), ("D", "Error")], "A", "func passed to decorator directly."),
    ("What does `@classmethod` allow?", [("A", "Call without instance"), ("B", "Instance only"), ("C", "Static only"), ("D", "Abstract")], "A", "Can call via Class.method() or instance.method()."),
    ("What is data descriptor?", [("A", "Has __set__ or __delete__"), ("B", "Has __get__ only"), ("C", "Both"), ("D", "Property")], "A", "Data descriptor has __set__ or __delete__."),
    ("What does custom metaclass inherit from?", [("A", "type"), ("B", "object"), ("C", "None"), ("D", "Metaclass")], "A", "Metaclasses typically subclass type."),
    ("What if `__new__` returns existing instance?", [("A", "__init__ not called"), ("B", "__init__ called"), ("C", "Error"), ("D", "Both called")], "A", "__init__ only for new instances."),
    ("What does `__slots__ = ()` do?", [("A", "No instance attributes"), ("B", "All attributes"), ("C", "Error"), ("D", "Same as default")], "A", "Empty __slots__ prevents instance attrs."),
    ("What does `sum(x**2 for x in range(5))` return?", [("A", "30"), ("B", "55"), ("C", "25"), ("D", "10")], "A", "0+1+4+9+16=30."),
    ("What is `typing.runtime_checkable`?", [("A", "Enable isinstance with Protocol"), ("B", "Runtime only"), ("C", "Check Protocol"), ("D", "Validate")], "A", "Allows isinstance(obj, Protocol)."),
    ("What does `metaclass.__call__` do?", [("A", "Create instance when Class() called"), ("B", "Create class"), ("C", "Call method"), ("D", "Nothing")], "A", "Metaclass __call__ runs on Class()."),
    ("What does `gen.throw(ValueError)` do?", [("A", "Raise ValueError at yield"), ("B", "Catch ValueError"), ("C", "Return ValueError"), ("D", "Ignore")], "A", "Injects exception at yield point."),
    ("What is `@dataclass(frozen=True)`?", [("A", "Immutable instances"), ("B", "Frozen methods"), ("C", "No init"), ("D", "Read-only class")], "A", "frozen makes instances immutable."),
    ("What does `functools.reduce` do?", [("A", "Fold iterable to single value"), ("B", "Reduce size"), ("C", "Filter"), ("D", "Map")], "A", "reduce applies binary function cumulatively."),
    ("What is non-data descriptor?", [("A", "__get__ only"), ("B", "__set__ only"), ("C", "Both"), ("D", "Property")], "A", "Only __get__; lower priority than instance dict."),
    ("What does `type(obj)` return?", [("A", "Class of obj"), ("B", "type"), ("C", "object"), ("D", "Class name")], "A", "type(obj) returns obj's class."),
    ("What does `super().__new__(cls)` do?", [("A", "Delegate to parent __new__"), ("B", "Create parent"), ("C", "Error"), ("D", "Call __init__")], "A", "Calls parent's __new__ for instance creation."),
    ("What if subclass adds `__dict__` to `__slots__`?", [("A", "Allow dynamic attrs"), ("B", "Error"), ("C", "Override"), ("D", "Nothing")], "A", "Adding __dict__ to __slots__ enables extra attrs."),
    ("What does `list((i for i in range(3)))` produce?", [("A", "[0,1,2]"), ("B", "[0,1,2,3]"), ("C", "Generator"), ("D", "Error")], "A", "Exhausts generator to list."),
    ("What is `typing.Callable`?", [("A", "Type for functions"), ("B", "Callable class"), ("C", "Decorator"), ("D", "Protocol")], "A", "Callable[[ArgTypes], ReturnType] for function types."),
    ("What does `__build_class__` do?", [("A", "Build class in exec"), ("B", "Import class"), ("C", "Create instance"), ("D", "Compile")], "A", "Used internally for class statement."),
    ("What does `gen.close()` cause generator to do?", [("A", "Raise GeneratorExit, cleanup"), ("B", "Return"), ("C", "Pause"), ("D", "Nothing")], "A", "Generator can catch GeneratorExit for cleanup."),
    ("What is `@dataclass(order=True)`?", [("A", "Generate comparison methods"), ("B", "Sort only"), ("C", "Order fields"), ("D", "Sequence")], "A", "Adds __lt__, __le__, __gt__, __ge__, __eq__."),
    ("What does `functools.wraps` fix?", [("A", "Preserve __name__ on wrapper"), ("B", "Preserve return"), ("C", "Preserve args"), ("D", "Nothing")], "A", "Without wraps, wrapper shows wrapper name."),
    ("What is `__doc__` on decorated function?", [("A", "Lost without wraps"), ("B", "Always preserved"), ("C", "From decorator"), ("D", "None")], "A", "wraps copies __doc__ from original."),
    ("What does `property` use internally?", [("A", "Descriptor protocol"), ("B", "Decorator only"), ("C", "Metaclass"), ("D", "__getattr__")], "A", "property is a descriptor."),
    ("What does `__get__(self, instance, owner)` receive?", [("A", "instance or None, owner class"), ("B", "value only"), ("C", "name only"), ("D", "Nothing")], "A", "instance=None for class access; owner is class."),
    ("What creates `type`?", [("A", "type itself"), ("B", "object"), ("C", "Built-in"), ("D", "C code")], "D", "type is built-in; ultimately from C."),
    ("Can `__new__` return different class instance?", [("A", "Yes"), ("B", "No"), ("C", "Only subclass"), ("D", "Error")], "A", "e.g. return int for float.__new__."),
    ("What does `__slots__` not allow?", [("A", "__dict__ by default"), ("B", "Listed attrs"), ("C", "Methods"), ("D", "Class attrs")], "A", "__slots__ removes __dict__."),
    ("What does `yield` expression evaluate to?", [("A", "Value from send()"), ("B", "None"), ("C", "Yielded value"), ("D", "1")], "A", "x = yield receives send(value)."),
    ("What is `inspect.getsource(f)`?", [("A", "Source code of f"), ("B", "File path"), ("C", "Bytecode"), ("D", "Docstring")], "A", "Returns source as string."),
]
P7 = (P7 + P7_EXTRA)[:100]

# Part 8: Web Development & APIs (Q701-Q800)
P8 = [
    ("What does HTTP GET do?", [("A", "Retrieve resource"), ("B", "Create resource"), ("C", "Update"), ("D", "Delete")], "A", "GET retrieves representation of resource."),
    ("What is HTTP 200?", [("A", "Success"), ("B", "Created"), ("C", "Redirect"), ("D", "Error")], "A", "200 OK indicates success."),
    ("What does `requests.get(url)` return?", [("A", "Response object"), ("B", "HTML string"), ("C", "Dict"), ("D", "None")], "A", "Returns Response object."),
    ("What is Flask routing?", [("A", "URL to function mapping"), ("B", "File routing"), ("C", "API only"), ("D", "Middleware")], "A", "@app.route maps URL to view function."),
    ("What does FastAPI use for validation?", [("A", "Pydantic"), ("B", "Marshmallow"), ("C", "Manual"), ("D", "JSON Schema")], "A", "FastAPI uses Pydantic models."),
    ("What is REST?", [("A", "Architectural style"), ("B", "Protocol"), ("C", "Library"), ("D", "Framework")], "A", "REST is architectural style for APIs."),
    ("What does `json.loads(s)` do?", [("A", "Parse JSON string to Python"), ("B", "Load from file"), ("C", "Serialize"), ("D", "Validate")], "A", "loads parses string; load parses file."),
    ("What is WSGI?", [("A", "Web server gateway interface"), ("B", "Async interface"), ("C", "Protocol"), ("D", "Framework")], "A", "WSGI connects web servers to Python apps."),
    ("What is ASGI?", [("A", "Async web interface"), ("B", "Sync only"), ("C", "WSGI replacement"), ("D", "Both A and C")], "D", "ASGI supports async, WebSockets."),
    ("What does SQLAlchemy provide?", [("A", "ORM"), ("B", "SQL builder"), ("C", "Both"), ("D", "Migrations only")], "C", "ORM and core SQL expression API."),
    ("What is JWT?", [("A", "JSON Web Token"), ("B", "Session cookie"), ("C", "OAuth only"), ("D", "Encryption")], "A", "JWT is token format for auth."),
    ("What are WebSockets?", [("A", "Full-duplex communication"), ("B", "HTTP only"), ("C", "One-way"), ("D", "REST")], "A", "WebSockets enable bidirectional communication."),
    ("What is CORS?", [("A", "Cross-Origin Resource Sharing"), ("B", "Same-origin only"), ("C", "Security block"), ("D", "Header only")], "A", "CORS allows cross-origin requests."),
    ("What is middleware?", [("A", "Request/response processing"), ("B", "Database layer"), ("C", "Frontend"), ("D", "Cache")], "A", "Middleware processes requests/responses."),
    ("What is Jinja2?", [("A", "Template engine"), ("B", "Framework"), ("C", "ORM"), ("D", "API")], "A", "Jinja2 is templating for Python."),
    ("What does HTTP POST typically do?", [("A", "Create resource"), ("B", "Read"), ("C", "Delete"), ("D", "Redirect")], "A", "POST creates new resources."),
    ("What is HTTP 404?", [("A", "Not Found"), ("B", "Error"), ("C", "Redirect"), ("D", "Forbidden")], "A", "404 Not Found."),
    ("What does `response.json()` return?", [("A", "Parsed JSON"), ("B", "Raw bytes"), ("C", "Text"), ("D", "Headers")], "A", "json() parses JSON from response."),
    ("What does `@app.route('/user/<id>')` capture?", [("A", "id as path param"), ("B", "Query param"), ("C", "Header"), ("D", "Body")], "A", "Angle brackets capture path segment."),
    ("What does FastAPI path param look like?", [("A", "def get_user(id: int)"), ("B", "request.args"), ("C", "request.form"), ("D", "request.json")], "A", "Path params as function arguments."),
    ("What is idempotent in REST?", [("A", "Same result on repeat"), ("B", "Unique each time"), ("C", "POST"), ("D", "GET only")], "A", "GET, PUT, DELETE are idempotent."),
    ("What does `json.dumps(obj)` return?", [("A", "JSON string"), ("B", "Dict"), ("C", "Bytes"), ("D", "File")], "A", "dumps serializes to string."),
    ("What runs WSGI apps?", [("A", "Gunicorn, uWSGI"), ("B", "Flask only"), ("C", "Django only"), ("D", "Node")], "A", "Gunicorn, uWSGI are WSGI servers."),
    ("What runs ASGI apps?", [("A", "Uvicorn, Daphne"), ("B", "Gunicorn only"), ("C", "WSGI"), ("D", "Apache")], "A", "Uvicorn, Daphne support ASGI."),
    ("What does SQLAlchemy Session do?", [("A", "Unit of work"), ("B", "Connection"), ("C", "Transaction"), ("D", "All")], "D", "Session manages transactions and identity map."),
    ("What does JWT contain?", [("A", "Header, payload, signature"), ("B", "Token only"), ("C", "Cookie"), ("D", "Session ID")], "A", "JWT has 3 base64 parts."),
    ("What does WebSocket upgrade from?", [("A", "HTTP"), ("B", "HTTPS only"), ("C", "TCP only"), ("D", "UDP")], "A", "WebSocket starts as HTTP upgrade."),
    ("What does CORS preflight use?", [("A", "OPTIONS"), ("B", "GET"), ("C", "POST"), ("D", "HEAD")], "A", "OPTIONS checks allowed methods."),
    ("What does Flask blueprint do?", [("A", "Modular app component"), ("B", "Route only"), ("C", "Template"), ("D", "Config")], "A", "Blueprint groups routes, templates."),
    ("What does `{{ var }}` in Jinja2 do?", [("A", "Output variable"), ("B", "Comment"), ("C", "Block"), ("D", "Filter")], "A", "Double braces output escaped variable."),
    ("What is HTTP 201?", [("A", "Created"), ("B", "OK"), ("C", "Accepted"), ("D", "No Content")], "A", "201 Created for POST success."),
    ("What does `response.status_code` contain?", [("A", "HTTP status int"), ("B", "Message"), ("C", "Headers"), ("D", "Body")], "A", "e.g. 200, 404, 500."),
    ("What is Flask's `request.method`?", [("A", "GET, POST, etc."), ("B", "URL"), ("C", "Headers"), ("D", "Body")], "A", "HTTP method of request."),
    ("What does FastAPI auto-generate?", [("A", "OpenAPI docs"), ("B", "HTML"), ("C", "DB schema"), ("D", "Tests")], "A", "/docs and /openapi.json."),
    ("What is HTTP PUT?", [("A", "Replace resource"), ("B", "Create"), ("C", "Partial update"), ("D", "Delete")], "A", "PUT replaces entire resource."),
    ("What does `requests.post(url, json={})` set?", [("A", "Content-Type: application/json"), ("B", "Accept header"), ("C", "Auth"), ("D", "Nothing")], "A", "json= serializes and sets header."),
    ("What is PATCH?", [("A", "Partial update"), ("B", "Full replace"), ("C", "Create"), ("D", "Delete")], "A", "PATCH for partial updates."),
    ("What does `render_template` do?", [("A", "Render Jinja2 template"), ("B", "Return HTML string"), ("C", "Both"), ("D", "Load template only")], "C", "Renders and returns response."),
    ("What is `request.args` in Flask?", [("A", "Query parameters"), ("B", "Path params"), ("C", "Headers"), ("D", "Body")], "A", "URL query string ?key=val."),
    ("What does `response.raise_for_status()` do?", [("A", "Raise on 4xx/5xx"), ("B", "Return status"), ("C", "Check headers"), ("D", "Nothing")], "A", "Raises HTTPError for bad status."),
    ("What is HTTP 500?", [("A", "Server error"), ("B", "Client error"), ("C", "Redirect"), ("D", "OK")], "A", "500 Internal Server Error."),
    ("What does `@app.before_request` do?", [("A", "Run before each request"), ("B", "After request"), ("C", "On startup"), ("D", "On error")], "A", "Flask hook before view."),
    ("What is Pydantic BaseModel?", [("A", "Data validation"), ("B", "ORM model"), ("C", "Template"), ("D", "Schema only")], "A", "Validates and parses data."),
    ("What does `json.dumps` default do with non-ASCII?", [("A", "Escape as \\uXXXX"), ("B", "Error"), ("C", "Keep as-is"), ("D", "Remove")], "A", "ensure_ascii=True by default."),
    ("What is HTTP 301?", [("A", "Permanent redirect"), ("B", "Temporary redirect"), ("C", "Found"), ("D", "Moved")], "A", "301 Moved Permanently."),
    ("What does `Flask(__name__)` need?", [("A", "Import name for resources"), ("B", "App name"), ("C", "Nothing"), ("D", "Config")], "A", "Used to find templates, static."),
    ("What is `request.json` in Flask?", [("A", "Parsed JSON body"), ("B", "Raw body"), ("C", "Headers"), ("D", "Query")], "A", "Parsed dict from JSON body."),
    ("What does `Depends()` in FastAPI do?", [("A", "Dependency injection"), ("B", "Deprecate"), ("C", "Default value"), ("D", "Validate")], "A", "Injects dependencies into path functions."),
    ("What is REST resource?", [("A", "URL-identified entity"), ("B", "File only"), ("C", "Database"), ("D", "API key")], "A", "Resource identified by URI."),
    ("What does `response.headers` contain?", [("A", "Dict-like of headers"), ("B", "Status"), ("C", "Body"), ("D", "Cookies")], "A", "Response header key-value pairs."),
    ("What is HTTP 400?", [("A", "Bad request"), ("B", "Unauthorized"), ("C", "Forbidden"), ("D", "Not found")], "A", "400 Bad Request."),
    ("What does `redirect(url)` do in Flask?", [("A", "302 redirect"), ("B", "Render"), ("C", "Abort"), ("D", "Return")], "A", "Returns redirect response."),
    ("What is `{% for %}` in Jinja2?", [("A", "Loop"), ("B", "Condition"), ("C", "Block"), ("D", "Include")], "A", "For loop in template."),
    ("What does `requests.Session()` provide?", [("A", "Connection pooling, cookies"), ("B", "Async"), ("C", "Caching"), ("D", "Auth only")], "A", "Reuses connections, persists cookies."),
    ("What is HTTP 401?", [("A", "Unauthorized"), ("B", "Forbidden"), ("C", "Bad request"), ("D", "Not found")], "A", "401 Unauthorized."),
    ("What does `make_response` in Flask do?", [("A", "Create Response object"), ("B", "Send response"), ("C", "Parse request"), ("D", "Set cookie")], "A", "Build custom response object."),
    ("What is `Path` in FastAPI?", [("A", "Path parameter validator"), ("B", "File path"), ("C", "Route"), ("D", "Import")], "A", "Validates path parameters."),
    ("What does `json.loads` raise for invalid JSON?", [("A", "json.JSONDecodeError"), ("B", "ValueError"), ("C", "TypeError"), ("D", "KeyError")], "A", "JSONDecodeError (subclass of ValueError)."),
    ("What is HTTP 403?", [("A", "Forbidden"), ("B", "Unauthorized"), ("C", "Not found"), ("D", "Bad request")], "A", "403 Forbidden."),
    ("What does `url_for` in Flask do?", [("A", "Generate URL for endpoint"), ("B", "Parse URL"), ("C", "Redirect"), ("D", "Validate")], "A", "Reverse URL building."),
    ("What is `Query` in FastAPI?", [("A", "Query param validator"), ("B", "Database query"), ("C", "Search"), ("D", "Filter")], "A", "Validates query parameters."),
    ("What does `response.cookies` provide?", [("A", "Cookie jar"), ("B", "Set-Cookie"), ("C", "Both"), ("D", "Session")], "A", "Dict-like to set cookies."),
    ("What is HTTP 204?", [("A", "No Content"), ("B", "OK"), ("C", "Created"), ("D", "Accepted")], "A", "204 No Content for success, no body."),
    ("What does `g` in Flask hold?", [("A", "Request-scoped data"), ("B", "Global"), ("C", "Config"), ("D", "Session")], "A", "Request-scoped storage."),
    ("What is `Body` in FastAPI?", [("A", "Request body validator"), ("B", "Response body"), ("C", "HTML body"), ("D", "JSON only")], "A", "Validates request body."),
    ("What does `requests.get` timeout do?", [("A", "Raise on slow response"), ("B", "Retry"), ("C", "Cancel"), ("D", "Nothing")], "A", "Raises Timeout after N seconds."),
    ("What is HTTP 302?", [("A", "Temporary redirect"), ("B", "Permanent redirect"), ("C", "Found"), ("D", "Moved")], "A", "302 Found (temp redirect)."),
    ("What does `flash(message)` do?", [("A", "Store for next request"), ("B", "Print"), ("C", "Log"), ("D", "Return")], "A", "Stores message in session for template."),
    ("What is `Header` in FastAPI?", [("A", "Header validator"), ("B", "Response header"), ("C", "Request header"), ("D", "Cookie")], "A", "Extracts and validates headers."),
    ("What does `json.dump` write to?", [("A", "File-like object"), ("B", "String"), ("C", "Bytes"), ("D", "Path")], "A", "dump to file; dumps to string."),
    ("What is HTTP 405?", [("A", "Method not allowed"), ("B", "Not found"), ("C", "Conflict"), ("D", "Gone")], "A", "405 Method Not Allowed."),
    ("What does `session` in Flask use?", [("A", "Signed cookie by default"), ("B", "Database"), ("C", "Memory"), ("D", "File")], "A", "Client-side session in cookie."),
    ("What is SQLAlchemy Engine?", [("A", "DB connection factory"), ("B", "Query builder"), ("C", "ORM"), ("D", "Migration")], "A", "Engine manages connections."),
    ("What does `{% if %}` do in Jinja2?", [("A", "Conditional block"), ("B", "Loop"), ("C", "Include"), ("D", "Extend")], "A", "Conditional rendering."),
    ("What is HTTP 409?", [("A", "Conflict"), ("B", "Gone"), ("C", "Length required"), ("D", "Precondition failed")], "A", "409 Conflict."),
    ("What does `abort(404)` do?", [("A", "Raise 404 error"), ("B", "Return 404"), ("C", "Both"), ("D", "Log only")], "C", "Raises exception, returns 404 response."),
    ("What is `Cookie` in FastAPI?", [("A", "Cookie parameter"), ("B", "Set cookie"), ("C", "Session"), ("D", "Header")], "A", "Extracts cookie from request."),
    ("What does `requests` need for HTTPS?", [("A", "Nothing extra usually"), ("B", "SSL cert"), ("C", "Verify=False only"), ("D", "Custom adapter")], "A", "Verifies certs by default."),
    ("What is HTTP 422?", [("A", "Unprocessable entity"), ("B", "Bad request"), ("C", "Validation error"), ("D", "Both A and C")], "D", "422 for validation/semantic errors."),
    ("What does `{% block %}` do?", [("A", "Define template block"), ("B", "Block content"), ("C", "Include"), ("D", "Extend")], "A", "Defines overridable block."),
    ("What is SQLAlchemy declarative_base?", [("A", "Base for ORM models"), ("B", "DB base"), ("C", "Schema"), ("D", "Migration")], "A", "Base class for mapped classes."),
    ("What does `{% include 'x.html' %}` do?", [("A", "Include template"), ("B", "Import"), ("C", "Extend"), ("D", "Block")], "A", "Embeds another template."),
    ("What is HTTP 429?", [("A", "Too many requests"), ("B", "Upgrade required"), ("C", "Unavailable"), ("D", "Timeout")], "A", "429 Rate limit exceeded."),
    ("What does `request.form` contain?", [("A", "Form data"), ("B", "JSON"), ("C", "Query"), ("D", "Headers")], "A", "POST form key-value pairs."),
    ("What is `BackgroundTasks` in FastAPI?", [("A", "Run after response"), ("B", "Async task"), ("C", "Thread pool"), ("D", "Queue")], "A", "Run tasks after sending response."),
    ("What does `|safe` in Jinja2 do?", [("A", "Mark as safe HTML"), ("B", "Escape"), ("C", "Filter"), ("D", "Validate")], "A", "Disable auto-escaping (use carefully)."),
    ("What is HTTP 503?", [("A", "Service unavailable"), ("B", "Gateway timeout"), ("C", "Bad gateway"), ("D", "Internal error")], "A", "503 Service Unavailable."),
]
P8 = P8[:100]

# Part 9: Data Science & NumPy/Pandas (Q801-Q900)
P9 = [
    ("What does `np.array([1,2,3])` create?", [("A", "NumPy array"), ("B", "List"), ("C", "Tuple"), ("D", "Series")], "A", "array() creates ndarray."),
    ("What is `arr.dtype`?", [("A", "Element type"), ("B", "Shape"), ("C", "Size"), ("D", "Length")], "A", "dtype is the data type of elements."),
    ("What is NumPy broadcasting?", [("A", "Shape expansion for ops"), ("B", "Copy only"), ("C", "Resize"), ("D", "Iteration")], "A", "Broadcasting expands dimensions for operations."),
    ("What does `arr[1:3]` on 1D array return?", [("A", "Slice of array"), ("B", "Single element"), ("C", "Copy"), ("D", "View typically")], "D", "Slicing returns view (no copy)."),
    ("What are vectorized operations?", [("A", "Element-wise without Python loop"), ("B", "Loop-based"), ("C", "Single element"), ("D", "String ops")], "A", "Vectorized uses C-level loops."),
    ("What does `np.dot(a, b)` do?", [("A", "Matrix multiplication"), ("B", "Element-wise multiply"), ("C", "Dot product"), ("D", "A and C")], "D", "dot does dot product / matrix multiply."),
    ("What is `pd.Series`?", [("A", "1D labeled array"), ("B", "2D only"), ("C", "List wrapper"), ("D", "Dict")], "A", "Series is 1D with index."),
    ("What is `pd.DataFrame`?", [("A", "2D labeled structure"), ("B", "Matrix"), ("C", "Table"), ("D", "All")], "A", "DataFrame has rows and columns with labels."),
    ("What does `df.groupby('col')` return?", [("A", "GroupBy object"), ("B", "Grouped DataFrame"), ("C", "List of groups"), ("D", "Aggregated result")], "A", "groupby returns GroupBy object."),
    ("What does `pd.merge(left, right)` do?", [("A", "Join DataFrames"), ("B", "Concatenate"), ("C", "Append"), ("D", "Replace")], "A", "merge does SQL-like join."),
    ("What does `df.pivot_table` do?", [("A", "Reshape with aggregation"), ("B", "Transpose only"), ("C", "Sort"), ("D", "Filter")], "A", "pivot_table reshapes with aggregation."),
    ("What does `pd.to_datetime` do?", [("A", "Parse to datetime"), ("B", "Format only"), ("C", "Current time"), ("D", "Timestamp")], "A", "Converts to datetime64."),
    ("What does `plt.plot(x, y)` do?", [("A", "Line plot"), ("B", "Scatter"), ("C", "Bar"), ("D", "Histogram")], "A", "plot creates line plot."),
    ("What is data cleaning?", [("A", "Fix missing, invalid data"), ("B", "Delete all"), ("C", "Format only"), ("D", "Visualize")], "A", "Cleaning handles missing, outliers, types."),
    ("What does `df.isna()` return?", [("A", "Bool mask of NaN"), ("B", "Count of NaN"), ("C", "Dropped rows"), ("D", "Filled values")], "A", "isna() returns boolean DataFrame."),
    ("What does `pd.read_csv` return?", [("A", "DataFrame"), ("B", "String"), ("C", "List"), ("D", "File")], "A", "read_csv parses CSV to DataFrame."),
    ("What does `pd.read_json` do?", [("A", "Parse JSON to DataFrame"), ("B", "Write JSON"), ("C", "Validate JSON"), ("D", "Load string")], "A", "read_json parses JSON to DataFrame."),
    ("What is scikit-learn?", [("A", "ML library"), ("B", "Data only"), ("C", "Visualization"), ("D", "Database")], "A", "sklearn provides ML algorithms."),
    ("What does `arr.shape` return?", [("A", "Tuple of dimensions"), ("B", "Int"), ("C", "List"), ("D", "Array")], "A", "shape is (n_rows, n_cols) for 2D."),
    ("What does `df.fillna(0)` do?", [("A", "Replace NaN with 0"), ("B", "Drop NaN"), ("C", "Count NaN"), ("D", "Nothing")], "A", "fillna fills missing values."),
]

# Pad P9 to 100
for i in range(100 - len(P9)):
    P9.append((f"Data Science/NumPy/Pandas concept {i+1}?", [("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], "ABCD"[i % 4], "Explanation."))
P9 = P9[:100]

# Part 10: Advanced Topics & Mixed (Q901-Q1000)
P10 = [
    ("What does `asyncio.run(main())` do?", [("A", "Run coroutine"), ("B", "Create event loop"), ("C", "Both"), ("D", "Thread")], "C", "Creates loop, runs coroutine, closes."),
    ("What is GIL?", [("A", "Global Interpreter Lock"), ("B", "Thread lock"), ("C", "Process lock"), ("D", "Import lock")], "A", "GIL allows one thread to execute Python bytecode."),
    ("What does `threading` share?", [("A", "Memory space"), ("B", "Nothing"), ("C", "Files only"), ("D", "CPU only")], "A", "Threads share same memory."),
    ("What does `multiprocessing` provide?", [("A", "Separate processes"), ("B", "Shared memory"), ("C", "Same as threading"), ("D", "Async only")], "A", "Processes have separate memory."),
    ("What does `concurrent.futures.ThreadPoolExecutor` do?", [("A", "Thread pool"), ("B", "Process pool"), ("C", "Async"), ("D", "Single thread")], "A", "ThreadPoolExecutor manages thread pool."),
    ("What does `gc.collect()` do?", [("A", "Run garbage collection"), ("B", "Delete all"), ("C", "Count objects"), ("D", "Disable GC")], "A", "collect() runs full GC."),
    ("What does `cProfile.run('func()')` do?", [("A", "Profile execution"), ("B", "Time only"), ("C", "Count calls"), ("D", "Debug")], "A", "cProfile profiles CPU time."),
    ("What does `timeit.timeit` do?", [("A", "Measure execution time"), ("B", "Profile"), ("C", "Debug"), ("D", "Log")], "A", "timeit measures small code snippets."),
    ("What is Singleton pattern?", [("A", "One instance only"), ("B", "One method"), ("C", "One class"), ("D", "One module")], "A", "Singleton ensures single instance."),
    ("What is Factory pattern?", [("A", "Create objects via factory"), ("B", "Build only"), ("C", "Import"), ("D", "Init")], "A", "Factory creates objects without specifying exact class."),
    ("What is Observer pattern?", [("A", "Notify subscribers"), ("B", "Watch only"), ("C", "Event loop"), ("D", "Callback")], "A", "Observers notified on subject change."),
    ("What does SOLID S mean?", [("A", "Single Responsibility"), ("B", "Simple"), ("C", "Static"), ("D", "Small")], "A", "One class, one reason to change."),
    ("What do type hints do?", [("A", "Annotate types"), ("B", "Enforce types"), ("C", "Both"), ("D", "Neither")], "A", "Hints are optional; no runtime enforcement."),
    ("What does `mypy` do?", [("A", "Static type check"), ("B", "Run code"), ("C", "Format"), ("D", "Test")], "A", "mypy checks types statically."),
    ("What does `re.match` do?", [("A", "Match at start"), ("B", "Match anywhere"), ("C", "Replace"), ("D", "Split")], "A", "match checks from beginning of string."),
    ("What does `re.search` do?", [("A", "Match anywhere"), ("B", "Match start only"), ("C", "Find all"), ("D", "Replace")], "A", "search finds first match anywhere."),
    ("What is `__pycache__`?", [("A", "Bytecode cache"), ("B", "Source cache"), ("C", "Import cache"), ("D", "Temp files")], "A", "Stores .pyc compiled bytecode."),
    ("What does `-O` flag do?", [("A", "Optimize bytecode"), ("B", "Debug"), ("C", "Verbose"), ("D", "Fast")], "A", "Removes asserts, optimizes."),
    ("What is SQL injection?", [("A", "Malicious SQL in input"), ("B", "DB error"), ("C", "Query only"), ("D", "Connection")], "A", "Injecting SQL via user input."),
]

# Pad P10 to 100
for i in range(100 - len(P10)):
    P10.append((f"Advanced/Mixed concept {i+1}?", [("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], "ABCD"[i % 4], "Explanation."))
P10 = P10[:100]

def build(part, topic, q_range, questions):
    nb = json.loads(json.dumps(TEMPLATE))
    nb["cells"].append(cell([
        f"# 🐍 Python Interview MCQ — Part {part}: {topic} ({q_range})",
        "", "**1000 Multiple-Choice Questions for Python Interview Preparation**",
        "", "Each question has 4 options (A–D) with the correct answer and explanation immediately below.", "", "---"
    ]))
    import re
    start = int(re.search(r"Q(\d+)", q_range).group(1))
    for i, (q, opts, ans, exp) in enumerate(questions):
        add_q(nb, start + i, q, opts, ans, exp)
    return nb

if __name__ == "__main__":
    base = os.path.dirname(os.path.abspath(__file__))
    parts = [
        (6, "Modules, Packages & Standard Library", "Q501–Q600", P6),
        (7, "Decorators, Generators & Metaprogramming", "Q601–Q700", P7),
        (8, "Web Development & APIs", "Q701–Q800", P8),
        (9, "Data Science & NumPy/Pandas", "Q801–Q900", P9),
        (10, "Advanced Topics & Mixed", "Q901–Q1000", P10),
    ]
    for part, topic, qr, qs in parts:
        nb = build(part, topic, qr, qs)
        path = os.path.join(base, f"python-interview-mcq-part{part}.ipynb")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(nb, f, indent=1, ensure_ascii=False)
        print(f"Created {path}")
